"""A2: generate 50 real AI-generated videos (3 generators) via a single script.

Designed for the TANBO plan when the local machine has ~4GB VRAM:
- Run this script on Colab / cloud GPU.
- It generates videos into data/source/<generator>/
- Writes data/source_manifest.jsonl
- Optionally bundles data/ into a zip for download.

Generators implemented (all via diffusers):
1) CogVideoX (T2V)  — if CogVideoXPipeline is available
2) SVD (I2V)        — Stable Video Diffusion; input images are generated by SD v1.5 (T2I)
3) Text2Video-SD    — as a practical open-source 3rd T2V source (damo-vilab/text-to-video-ms-1.7b)

Note:
- Open-Sora is not pinned here because its ecosystem is fragmented and repo-specific.
  This script provides a stable third open-source generator to satisfy the “>=3 generators” requirement.
  If you must use Open-Sora specifically, keep the output format identical and swap generator 3.

Example (Colab):
  pip install -U diffusers transformers accelerate safetensors imageio imageio-ffmpeg pillow
  python infra/scripts/a2_generate_videos.py --out-root . --zip

Output structure (relative to --out-root):
  data/source/cogvideox/real_cog_001.mp4
  data/source/svd/real_svd_001.mp4
  data/source/t2vms/real_t2v_001.mp4
  data/source_manifest.jsonl
"""

from __future__ import annotations

import argparse
import json
import os
import random
import shutil
import sys
import gc
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional


def configure_hf(mirror: str | None = None) -> None:
    """Configure HuggingFace Hub endpoint.

    This is useful when the default hub endpoint is unstable/blocked.
    """

    if mirror:
        # Used by huggingface_hub + transformers.
        os.environ["HF_ENDPOINT"] = mirror
        print(f"[hf] HF_ENDPOINT set to: {mirror}")


def default_out_root() -> Path:
    """Prefer CWD so the script can be uploaded standalone to Colab."""
    return Path.cwd()


def write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def make_prompts(n: int, seed: int) -> list[str]:
    random.seed(seed)

    scenes = [
        "a small cafe",
        "a modern kitchen",
        "a busy city street",
        "a quiet office",
        "a living room",
        "a park on a sunny day",
        "a train station",
        "a supermarket aisle",
        "a classroom",
        "a gym",
    ]
    actions = [
        "walks into the scene and sits down",
        "runs across the scene and stops",
        "picks up a cup and takes a sip",
        "opens a door and waves to the camera",
        "points at a sign and then looks back",
        "stands up, turns around, and leaves",
    ]
    subjects = [
        "a woman in a red dress",
        "a man in a suit",
        "two friends",
        "a chef",
        "a teacher",
        "a child with a backpack",
    ]
    styles = [
        "photorealistic, handheld camera, natural lighting",
        "cinematic, shallow depth of field, high detail",
        "documentary style, stable camera, realistic colors",
    ]

    prompts: list[str] = []
    while len(prompts) < n:
        s = random.choice(subjects)
        scene = random.choice(scenes)
        act = random.choice(actions)
        st = random.choice(styles)
        p = f"{s} in {scene} {act}. {st}."
        if p not in prompts:
            prompts.append(p)
    return prompts


def _try_enable_low_vram(pipe: Any) -> None:
    # Best-effort VRAM savers.
    try:
        pipe.enable_model_cpu_offload()
    except Exception:
        pass
    try:
        pipe.enable_sequential_cpu_offload()
    except Exception:
        pass
    try:
        pipe.enable_attention_slicing()
    except Exception:
        pass
    try:
        pipe.enable_vae_slicing()
    except Exception:
        pass
    try:
        if hasattr(pipe, "vae") and pipe.vae is not None:
            pipe.vae.enable_slicing()
    except Exception:
        pass
    try:
        if hasattr(pipe, "vae") and pipe.vae is not None:
            pipe.vae.enable_tiling()
    except Exception:
        pass


def _maybe_empty_cuda() -> None:
    try:
        import torch

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:
        pass


def _cleanup(obj: Any) -> None:
    try:
        del obj
    except Exception:
        pass
    gc.collect()
    _maybe_empty_cuda()


def _pipe_call(pipe: Any, **kwargs: Any) -> Any:
    """Call a diffusers pipeline in inference mode."""
    try:
        import torch

        with torch.inference_mode():
            return pipe(**kwargs)
    except Exception:
        return pipe(**kwargs)


def _extract_frames(result: Any) -> list[Any]:
    """Normalize diffusers output -> list[frames] for export_to_video."""
    if hasattr(result, "frames") and result.frames is not None:
        # Common: result.frames = [frames]
        frames = result.frames[0] if isinstance(result.frames, (list, tuple)) else result.frames
        return frames
    if hasattr(result, "videos") and result.videos is not None:
        # videos: numpy/torch tensor [B, F, H, W, C]
        return result.videos[0]
    if hasattr(result, "images") and result.images is not None:
        imgs = result.images
        if isinstance(imgs, (list, tuple)):
            return imgs
        return [imgs]
    raise RuntimeError("Unknown diffusers output format; cannot extract frames")


@dataclass
class GenSpec:
    name: str
    out_dir: Path
    id_prefix: str


def generate_cogvideox(
    spec: GenSpec,
    prompts: list[str],
    n: int,
    fps: int,
    num_frames: int,
    seed: int,
) -> list[dict[str, Any]]:
    try:
        import torch
        from diffusers.utils import export_to_video
        from diffusers import CogVideoXPipeline
    except Exception as e:
        print(f"[cogvideox] unavailable: {repr(e)}")
        return []

    model_id = os.environ.get("COGVIDEOX_MODEL", "zai-org/CogVideoX-2b")
    pipe = CogVideoXPipeline.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
    )
    _try_enable_low_vram(pipe)

    cog_steps_env = os.environ.get("COGVIDEOX_STEPS")
    num_inference_steps = int(cog_steps_env) if cog_steps_env else 50

    records: list[dict[str, Any]] = []
    for i in range(n):
        vid_id = f"{spec.id_prefix}{i+1:03d}"
        prompt = prompts[i]
        mp4_path = spec.out_dir / f"{vid_id}.mp4"
        gen_device = "cuda" if torch.cuda.is_available() else "cpu"
        g = torch.Generator(device=gen_device).manual_seed(seed + i)

        result = _pipe_call(
            pipe,
            prompt=prompt,
            num_videos_per_prompt=1,
            num_inference_steps=num_inference_steps,
            num_frames=num_frames,
            guidance_scale=6.0,
            generator=g,
        )
        # Official output for CogVideoX is typically `frames`.
        try:
            video = result.frames[0]
        except Exception:
            video = _extract_frames(result)
        export_to_video(video, str(mp4_path), fps=fps)

        records.append(
            {
                "id": vid_id,
                "video_path": str(mp4_path),
                "shotir_path": None,
                "generator": "cogvideox-2b",
                "prompt": prompt,
                "meta": {"fps": fps, "num_frames": num_frames, "num_inference_steps": num_inference_steps},
            }
        )
        print(f"[cogvideox] done {vid_id}")

    _cleanup(pipe)
    return records


def generate_t2i_images(
    out_dir: Path,
    prompts: list[str],
    n: int,
    seed: int,
) -> list[Path]:
    """Generate images for SVD using SD v1.5 (keeps pipeline self-contained)."""
    try:
        import torch
        from diffusers import StableDiffusionPipeline
    except Exception as e:
        raise RuntimeError(f"StableDiffusionPipeline unavailable: {repr(e)}")

    model_id = os.environ.get("SVD_T2I_MODEL", "runwayml/stable-diffusion-v1-5")
    pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
    _try_enable_low_vram(pipe)

    images: list[Path] = []
    for i in range(n):
        img_id = f"svd_input_{i+1:03d}"
        img_path = out_dir / f"{img_id}.png"
        g = torch.Generator(device="cuda" if torch.cuda.is_available() else "cpu").manual_seed(seed + 10_000 + i)
        call_kwargs: dict[str, Any] = {
            "prompt": prompts[i],
            "num_inference_steps": 25,
            "guidance_scale": 7.0,
            "generator": g,
        }
        img = _pipe_call(pipe, **call_kwargs).images[0]
        img.save(img_path)
        images.append(img_path)
        print(f"[t2i] done {img_id}")
    _cleanup(pipe)
    return images


def generate_svd(
    spec: GenSpec,
    prompts: list[str],
    n: int,
    fps: int,
    num_frames: int,
    seed: int,
    tmp_dir: Path,
    num_inference_steps: int | None = None,
) -> list[dict[str, Any]]:
    try:
        import torch
        from PIL import Image
        from diffusers.utils import export_to_video
        from diffusers import StableVideoDiffusionPipeline
    except Exception as e:
        print(f"[svd] unavailable: {repr(e)}")
        return []

    model_id = os.environ.get("SVD_MODEL", "stabilityai/stable-video-diffusion-img2vid-xt")
    pipe = StableVideoDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
    _try_enable_low_vram(pipe)

    img_dir = tmp_dir / "svd_input_images"
    img_dir.mkdir(parents=True, exist_ok=True)
    images = generate_t2i_images(img_dir, prompts, n=n, seed=seed)

    records: list[dict[str, Any]] = []
    for i, img_path in enumerate(images):
        vid_id = f"{spec.id_prefix}{i+1:03d}"
        mp4_path = spec.out_dir / f"{vid_id}.mp4"
        g = torch.Generator(device="cuda" if torch.cuda.is_available() else "cpu").manual_seed(seed + 20_000 + i)

        image = Image.open(img_path).convert("RGB")
        call_kwargs: dict[str, Any] = {"image": image, "num_frames": num_frames, "generator": g}
        if num_inference_steps is not None:
            call_kwargs["num_inference_steps"] = int(num_inference_steps)
        try:
            result = _pipe_call(pipe, **call_kwargs)
        except TypeError:
            # Some versions don't accept num_inference_steps
            call_kwargs.pop("num_inference_steps", None)
            result = _pipe_call(pipe, **call_kwargs)
        frames = _extract_frames(result)
        export_to_video(frames, str(mp4_path), fps=fps)

        records.append(
            {
                "id": vid_id,
                "video_path": str(mp4_path),
                "shotir_path": None,
                "generator": "svd-img2vid-xt",
                "prompt": prompts[i],
                "meta": {"fps": fps, "num_frames": num_frames, "input_image": str(img_path)},
            }
        )
        print(f"[svd] done {vid_id}")

    _cleanup(pipe)
    return records


def generate_t2vms(
    spec: GenSpec,
    prompts: list[str],
    n: int,
    fps: int,
    num_frames: int,
    seed: int,
    num_inference_steps: int | None = None,
) -> list[dict[str, Any]]:
    """Third generator: text-to-video-ms (diffusers TextToVideoSDPipeline)."""
    try:
        import torch
        from diffusers.utils import export_to_video
        from diffusers import TextToVideoSDPipeline
    except Exception as e:
        print(f"[t2vms] unavailable: {repr(e)}")
        return []

    model_id = os.environ.get("T2VMS_MODEL", "damo-vilab/text-to-video-ms-1.7b")
    pipe = TextToVideoSDPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
    _try_enable_low_vram(pipe)

    records: list[dict[str, Any]] = []
    for i in range(n):
        vid_id = f"{spec.id_prefix}{i+1:03d}"
        prompt = prompts[i]
        mp4_path = spec.out_dir / f"{vid_id}.mp4"
        g = torch.Generator(device="cuda" if torch.cuda.is_available() else "cpu").manual_seed(seed + 30_000 + i)

        # Many video pipelines accept num_frames / num_inference_steps.
        call_kwargs: dict[str, Any] = {
            "prompt": prompt,
            "num_frames": num_frames,
            "generator": g,
            "num_inference_steps": int(num_inference_steps) if num_inference_steps is not None else 25,
        }
        result = _pipe_call(pipe, **call_kwargs)
        frames = _extract_frames(result)
        export_to_video(frames, str(mp4_path), fps=fps)

        records.append(
            {
                "id": vid_id,
                "video_path": str(mp4_path),
                "shotir_path": None,
                "generator": "text-to-video-ms-1.7b",
                "prompt": prompt,
                "meta": {"fps": fps, "num_frames": num_frames},
            }
        )
        print(f"[t2vms] done {vid_id}")

    _cleanup(pipe)
    return records


def main() -> None:
    # Configure HuggingFace mirror early (before any from_pretrained/download calls).
    configure_hf(mirror="https://hf-mirror.com")

    parser = argparse.ArgumentParser(description="A2: generate 3-generator source videos + manifest")
    parser.add_argument(
        "--out-root",
        default=str(default_out_root()),
        help="Directory where data/ will be written (default: current working directory)",
    )
    parser.add_argument("--duration-s", type=int, default=6)
    parser.add_argument("--fps", type=int, default=8)
    parser.add_argument("--seed", type=int, default=20260403)

    # Speed/memory knobs (use these on Colab if you get "Killed" / OOM)
    parser.add_argument("--t2i-steps", type=int, default=25, help="SD steps for SVD input images")
    parser.add_argument("--t2v-steps", type=int, default=25, help="Steps for text-to-video-ms")
    parser.add_argument("--svd-steps", type=int, default=None, help="Steps for SVD (if supported by your diffusers)")

    parser.add_argument("--n-cog", type=int, default=20)
    parser.add_argument("--n-svd", type=int, default=15)
    parser.add_argument("--n-t2v", type=int, default=15)

    parser.add_argument("--zip", action="store_true", help="Create a zip bundle containing data/")
    parser.add_argument("--keep-tmp", action="store_true", help="Keep temporary files")

    # Notebook runtimes (Colab/Jupyter) may inject extra args (e.g. -f <kernel.json>).
    # Use parse_known_args so the script can be run via %run / notebook launchers.
    args, unknown = parser.parse_known_args()
    if unknown:
        print(f"[a2_generate_videos] Ignoring unknown args: {unknown}")

    # Dependency preflight (common on Colab): diffusers may require a newer Pillow.
    # In notebooks, raising SystemExit can sometimes trigger noisy IPython tracebacks;
    # prefer a clean message + return.
    try:
        import PIL  # type: ignore
        import PIL._typing as pil_typing  # type: ignore

        if not hasattr(pil_typing, "_Ink"):
            raise RuntimeError(
                "Pillow is too old for the installed diffusers pipelines (missing PIL._typing._Ink)."
            )
        print(f"[deps] Pillow {getattr(PIL, '__version__', 'unknown')} OK")
    except Exception as e:
        print("[deps] Dependency check failed:")
        print("  ", repr(e))
        print("[deps] Fix on Colab (run in a fresh cell, then re-run this script):")
        print("  pip install -U --force-reinstall 'pillow>=11' 'diffusers>=0.30' transformers accelerate safetensors")
        return

    root = Path(args.out_root).resolve()
    data_root = root / "data"
    source_root = data_root / "source"

    tmp_dir = root / ".a2_tmp"
    tmp_dir.mkdir(parents=True, exist_ok=True)

    num_frames = int(args.duration_s * args.fps + 1)
    total = int(args.n_cog + args.n_svd + args.n_t2v)
    prompts = make_prompts(total, seed=int(args.seed))

    # Output dirs
    cog_dir = source_root / "cogvideox"
    svd_dir = source_root / "svd"
    t2v_dir = source_root / "t2vms"
    for d in [cog_dir, svd_dir, t2v_dir]:
        d.mkdir(parents=True, exist_ok=True)

    all_records: list[dict[str, Any]] = []

    # 1) CogVideoX
    all_records.extend(
        generate_cogvideox(
            GenSpec("cogvideox", cog_dir, "real_cog_"),
            prompts[: args.n_cog],
            n=int(args.n_cog),
            fps=int(args.fps),
            num_frames=num_frames,
            seed=int(args.seed),
        )
    )

    # 2) SVD (uses next prompts for t2i images)
    start = int(args.n_cog)
    all_records.extend(
        generate_svd(
            GenSpec("svd", svd_dir, "real_svd_"),
            prompts[start : start + args.n_svd],
            n=int(args.n_svd),
            fps=int(args.fps),
            num_frames=num_frames,
            seed=int(args.seed),
            tmp_dir=tmp_dir,
            num_inference_steps=args.svd_steps,
        )
    )

    # 3) Text2Video-MS (third generator)
    start = int(args.n_cog + args.n_svd)
    all_records.extend(
        generate_t2vms(
            GenSpec("t2vms", t2v_dir, "real_t2v_"),
            prompts[start : start + args.n_t2v],
            n=int(args.n_t2v),
            fps=int(args.fps),
            num_frames=num_frames,
            seed=int(args.seed),
            num_inference_steps=int(args.t2v_steps),
        )
    )

    # Normalize manifest paths to be repo-relative + POSIX-style.
    manifest_records: list[dict[str, Any]] = []
    for r in all_records:
        vp = Path(r["video_path"]).resolve()
        r2 = dict(r)
        r2["video_path"] = rel_posix(vp, root)
        r2["shotir_path"] = None
        # Keep generator folder as a field for later stats.
        if r2.get("generator") and "generator" not in r2:
            r2["generator"] = r2["generator"]
        manifest_records.append(r2)

    manifest_path = data_root / "source_manifest.jsonl"
    write_jsonl(manifest_path, manifest_records)
    print(f"Wrote manifest: {manifest_path}")
    print(f"Total generated: {len(manifest_records)}")

    requested = int(args.n_cog) + int(args.n_svd) + int(args.n_t2v)
    if requested > 0 and len(manifest_records) == 0:
        print("No videos were generated. See errors above.")
        return

    if not args.keep_tmp:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    if args.zip:
        zip_base = str(root / "videogendoctor_a2_bundle")
        # Zip only data/ for clean merge on local machine.
        zip_path = shutil.make_archive(zip_base, "zip", root_dir=str(root), base_dir="data")
        print(f"Zip written: {zip_path}")


if __name__ == "__main__":
    main()
